### ISSUE TITLE
Create full-blown ZYLISP REPL

### ISSUE THREAD

**Issue by oubiwann** [zylisp/zylisp#23]
Features/tasks:
* [ ] Abstract banner setup for easy reuse by all three REPLs (AST, Go, Lisp)
* [ ] Create evaluator - #24
* [ ] Ensure that the evaluator works with the current reader
* [ ] Create a results printer
* [ ] Add readline/line editing support
